replicaCount: 2

image:
  repository: atmaram/fff-ui
  tag: latest
  pullPolicy: Always

targetEnv:
  name: Prod

service:
  name: ui
  port: 3000
  targetPort: 3000
  nodePort: 30300

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 128Mi