replicaCount: 2

image:
  repository: atmaram/fff-ui
  tag: latest
  pullPolicy: Always

targetEnv:
  name: Devlopment

service:
  name: ui
  port: 3000
  targetPort: 3000
  nodePort: 30100

resources:
   limits:
     cpu: 90m
     memory: 300Mi
   requests:
     cpu: 30m
     memory: 128Mi