replicaCount: 2

image:
  repository: atmaram/fff-ui
  tag: latest
  pullPolicy: Always

targetEnv:
  name: QA

service:
  name: ui
  port: 80
  targetPort: 80
  nodePort: 30200

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 128Mi